name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.5
          cache: 'npm'
      - name: Installing Dependencies
        run: npm ci
      - name: Running Tests
        run: npm test

  generate-blog-database:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Generating Dynamic Blog Links
        run: npm run generate-dynamic-blogs

  build:
    needs: generate-blog-database
    runs-on: ubuntu-latest

    steps:
      - name: Building
        run: npm run build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
          retention-days: 30

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: contains('refs/heads/master', github.ref)

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Login to AWS
        if: ${{ success() }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.JEVES_AWS_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.JEVES_AWS_SECRET_ACCESS_TOKEN }}
          aws-region: us-east-2

      - name: Upload to AWS S3
        run: aws --delete s3 sync ./build s3://obscurelymeclub
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION }} --paths "/index.html"
