name: Actions

on:
  push:
    branches: [master]
  pull_requests:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@2
        with:
          node-version: 14.17.5
          cache: 'npm'
      - run: npm test
      - run: npm build
